In [1]:
#dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timezone
pd.set_option('display.max_columns', 50)

In [2]:
#import csv data files
# File to Load 
ad_data_to_load = "csv_data/Ad3.csv"
cost_of_goods_to_load = "csv_data/cost_of_goods.csv"
transactions_to_load="csv_data/transactions_main.csv"

# Read the City and Ride Data
ad_data_raw =pd.read_csv(ad_data_to_load, index_col=False)
cost_of_goods_raw =pd.read_csv(cost_of_goods_to_load)
transactions_raw =pd.read_csv(transactions_to_load)

#create dfs
ad_df_raw = pd.DataFrame(ad_data_raw)
cog_df_raw = pd.DataFrame(cost_of_goods_raw)
trans_df_raw = pd.DataFrame(transactions_raw)

#merge trans df and cost of goods df
combo_df =pd.merge(trans_df_raw, cog_df_raw, how='inner', on='sku', left_on=None, right_on=None,
         left_index=False, right_index=False, sort=True,
         suffixes=('_x', '_y'), copy=True, indicator=False,
         validate=None)
#cog_df_raw.head()
combo_df.head(3)

,date/time,settlement id,type,order id,sku,description,quantity,marketplace,fulfillment,order city,order state,order postal,product sales,shipping credits,gift wrap credits,promotional rebates,sales tax collected,Marketplace Facilitator Tax,selling fees,fba fees,other transaction fees,other,total,asin,group,parent,child,est_cost_unit,pick_n_pack_fee
0,"Feb 7, 2017 8:23:12 AM PST",6287999201,Order,S01-3232416-6108561,1I-A550-7LTL,Bamboo Salt Box by Iconic Home,1.0,sim1.stores.amazon.com,Amazon,Lawrence,KS,66049,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-5.50,0.0,0.0,-5.50,B01N5TVYVD,Bamboo Salt Boxes,Bamboo Salt Box,Bamboo Salt Box,0.66,4.18
1,"Feb 7, 2017 8:23:12 AM PST",6287999201,Order,S01-3232416-6108561,1I-A550-7LTL,Bamboo Salt Box by Iconic Home,1.0,sim1.stores.amazon.com,Amazon,Lawrence,KS,66049,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.75,0.0,0.0,-0.75,B01N5TVYVD,Bamboo Salt Boxes,Bamboo Salt Box,Bamboo Salt Box,0.66,4.18
2,"Apr 11, 2017 6:48:27 PM PDT",6332587981,Order,S01-4313057-3681367,1I-A550-7LTL,Bamboo Salt Box by Iconic Home,1.0,sim1.stores.amazon.com,Amazon,St. Louis,MO,63139,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-8.50,0.0,0.0,-8.50,B01N5TVYVD,Bamboo Salt Boxes,Bamboo Salt Box,Bamboo Salt Box,0.66,4.18

In [3]:
combo_df.loc[:, 'date/time'].replace(regex=True,inplace=True,to_replace="PST", value="") #remove 'PST' from date/time; if PST or PDT remain an error will occur
combo_df.loc[:, 'date/time'].replace(regex=True,inplace=True,to_replace="PDT", value="") #remove 'PDT' from date/time; if PST or PDT remain an error will occur
combo_df['date/time']=pd.to_datetime(combo_df['date/time']) #keeps changes in place

combo_df.sort_values('date/time').head()

,date/time,settlement id,type,order id,sku,description,quantity,marketplace,fulfillment,order city,order state,order postal,product sales,shipping credits,gift wrap credits,promotional rebates,sales tax collected,Marketplace Facilitator Tax,selling fees,fba fees,other transaction fees,other,total,asin,group,parent,child,est_cost_unit,pick_n_pack_fee
345,2015-04-15 18:48:48,5893239421,Order,108-1163521-1001851,48-JT2Z-XFJ6,Chocolate Disney Frozen Surprise Egg By Zaini-...,1.0,amazon.com,Amazon,MANDAN,ND,58554-6280,21.99,0.00,3.49,0.0,0.0,0.0,-3.3,-6.16,0.0,0.0,16.02,NaN,NaN,Chocolate Eggs,Frozen Chocolate Eggs,2.31,NaN
8051,2015-04-17 12:47:22,5893239421,Order,110-1298678-8465031,B5-0ROP-233D,Chocolate Disney Princess Surprise Eggs (Set o...,1.0,amazon.com,Amazon,SPARKS,NV,89431-2753,21.99,3.99,0.00,0.0,0.0,0.0,-3.3,-6.66,0.0,0.0,16.02,NaN,NaN,Chocolate Eggs,Princess Chocolate Eggs,2.31,NaN
15171,2015-04-18 22:09:29,5893239421,Order,113-1855692-5237838,MU-6BI2-VLJV,Disney Cars Chocolate Surprise Eggs (Set of 3)...,1.0,amazon.com,Amazon,HIGHLAND BEACH,FLORIDA,33487-5378,21.99,0.00,0.00,0.0,0.0,0.0,-3.3,-2.67,0.0,0.0,16.02,NaN,NaN,Chocolate Eggs,Cars Chocolate Eggs,2.31,NaN
8060,2015-04-18 23:12:22,5893239421,Order,107-4125725-1491465,BF-MG8U-OWWI,Spider Man Chocolate Surprise Eggs (Set of 3) ...,1.0,amazon.com,Amazon,DALLAS,GA,30132-8525,21.99,3.99,0.00,0.0,0.0,0.0,-3.3,-6.66,0.0,0.0,16.02,NaN,NaN,Chocolate Eggs,Spider Man Chocolate Eggs,2.31,NaN
346,2015-04-20 00:18:22,5893239421,Order,112-0211196-0726645,48-JT2Z-XFJ6,Chocolate Disney Frozen Surprise Eggs (Set of ...,1.0,amazon.com,Amazon,miami,FL,33127,21.99,0.00,0.00,0.0,0.0,0.0,-3.3,-2.67,0.0,0.0,16.02,NaN,NaN,Chocolate Eggs,Frozen Chocolate Eggs,2.31,NaN

In [4]:
def trans_cols(x): #creates new cols and their calculations
    x['transaction revenue']= ""#revenue generate from transaction (revenue - cost of goods)
    x['sale price']= x['product sales']/x['quantity']#generates price of item at sale
    x['Day of Week']=""
    x['Cost of Goods']=""
    x['Whole Date'] =""
    
trans_cols(combo_df) #apply the trans_cols function

short_trans_df=combo_df.drop(['settlement id','order id','marketplace','fulfillment'],axis=1) #drop unimportant columns and create a smaller df
short_trans_df.head()

,date/time,type,sku,description,quantity,order city,order state,order postal,product sales,shipping credits,gift wrap credits,promotional rebates,sales tax collected,Marketplace Facilitator Tax,selling fees,fba fees,other transaction fees,other,total,asin,group,parent,child,est_cost_unit,pick_n_pack_fee,transaction revenue,sale price,Day of Week,Cost of Goods,Whole Date
0,2017-02-07 08:23:12,Order,1I-A550-7LTL,Bamboo Salt Box by Iconic Home,1.0,Lawrence,KS,66049,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-5.50,0.0,0.0,-5.50,B01N5TVYVD,Bamboo Salt Boxes,Bamboo Salt Box,Bamboo Salt Box,0.66,4.18,,0.0,,,
1,2017-02-07 08:23:12,Order,1I-A550-7LTL,Bamboo Salt Box by Iconic Home,1.0,Lawrence,KS,66049,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.75,0.0,0.0,-0.75,B01N5TVYVD,Bamboo Salt Boxes,Bamboo Salt Box,Bamboo Salt Box,0.66,4.18,,0.0,,,
2,2017-04-11 18:48:27,Order,1I-A550-7LTL,Bamboo Salt Box by Iconic Home,1.0,St. Louis,MO,63139,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-8.50,0.0,0.0,-8.50,B01N5TVYVD,Bamboo Salt Boxes,Bamboo Salt Box,Bamboo Salt Box,0.66,4.18,,0.0,,,
3,2017-04-11 18:48:27,Order,1I-A550-7LTL,Bamboo Salt Box by Iconic Home,1.0,St. Louis,MO,63139,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.75,0.0,0.0,-0.75,B01N5TVYVD,Bamboo Salt Boxes,Bamboo Salt Box,Bamboo Salt Box,0.66,4.18,,0.0,,,
4,2017-05-11 00:35:02,Order,1I-A550-7LTL,Bamboo Salt Box by Iconic Home,1.0,Wildwood,MO,63040,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-8.50,0.0,0.0,-8.50,B01N5TVYVD,Bamboo Salt Boxes,Bamboo Salt Box,Bamboo Salt Box,0.66,4.18,,0.0,,,

In [5]:
# from datetime import datetime
# date='Apr 10, 2015 5:25:27 PM'

# datetime_object = datetime.strptime(date, '%b %d, %Y %H:%M:%S %p')
# datetime_object

In [6]:
#TODO
#Everyone has repository clone
#Strategy for branching and merging. 
#Outline responsibilities
#